"""create many to many relations

Revision ID: d9d88200b8ec
Revises: f41f457c7e40
Create Date: 2023-10-08 15:30:44.459996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd9d88200b8ec'
down_revision: Union[str, None] = 'f41f457c7e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_user',
                    sa.Column('user_id', sa.Integer, sa.ForeignKey("users.id")),
                    sa.Column('ability_id', sa.Integer, sa.ForeignKey("abilities.id")),

                    )
    op.create_table('ability_token',
                    sa.Column('token_id', sa.Integer, sa.ForeignKey("access_tokens.id")),
                    sa.Column('ability_id', sa.Integer, sa.ForeignKey("abilities.id")),

                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ability_token')
    op.drop_table('ability_user')
    # ### end Alembic commands ###
